ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  paths:
    - /
  hosts:
    - host: delicate-flowers.bb-gke.hillghost.com
      paths: ["/"]
  tls:
    - secretName: delicate-flowers-cert
      hosts:
        - delicate-flowers.bb-gke.hillghost.com